# Используем официальный образ Nginx
FROM nginx:alpine

# Копируем все папки в директорию Nginx
COPY Web/login.html /usr/share/nginx/html
COPY Web/registration.html /usr/share/nginx/html
COPY Web/test.html /usr/share/nginx/html
COPY Web/css /usr/share/nginx/html/css
COPY Web/js /usr/share/nginx/html/js
COPY Web/image /usr/share/nginx/html/image

# Копируем конфигурационный файл
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт 80
EXPOSE 81
